stages:
  - install
  - build
  - test

debian:install:
  stage: install
  tags:
    - debian
  script:
    - sudo apt-get install -y cmake libusb-1.0-0-dev libldap2-dev libpam0g-dev doxygen graphviz

freebsd:install:
  stage: install
  script:
    - sudo pkg install -y cmake openldap-client doxygen graphviz
  tags:
    - freebsd

opensuse:install:
  stage: install
  script:
    - sudo zypper install -y cmake libusb-1_0-devel openldap2-devel pam-devel doxygen graphviz
  tags:
    - opensuse

.daemon:build: &daemon_build
  allow_failure: true
  stage: build
  before_script:
    - test -d _build && test -d out || ./bootstrap
  script:
    - make
  artifacts:
    name: "default-binaries-${CI_RUNNER_TAGS}"
    paths:
      - out/deviddctl
      - out/libpam_usbwall.so
      - out/usbwalld
    expire_in: 1h
#  cache: &cache_def
#    paths:
#      - _build/
#      - out/
#    key: ${CI_COMMIT_REF_SLUG}-${CI_RUNNER_TAGS}

daemon:debian:build:
  tags:
    - debian
  <<: *daemon_build

daemon:freebsd:build:
  tags:
    - freebsd
  <<: *daemon_build

daemon:opensuse:build:
  tags:
    - opensuse
  <<: *daemon_build

.testsuite:build: &testsuite_build
  allow_failure: true
  stage: build
  before_script:
    - test -d _build && test -d out || ./bootstrap
  script:
    - make test
  artifacts:
    name: "test-binary-${CI_RUNNER_TAGS}"
    paths:
      - out/usbwall_test
    expire_in: 1h
#  cache: *cache_def

testsuite:debian:build:
  tags:
    - debian
  <<: *testsuite_build

testsuite:freebsd:build:
  tags:
    - freebsd
  <<: *testsuite_build

testsuite:opensuse:build:
  tags:
    - opensuse
  <<: *testsuite_build

.doc:build: &doc_build
  allow_failure: true
  stage: build
  before_script:
    - test -d _build && test -d out || ./bootstrap
  script:
    - make doc
  artifacts:
    name: "documentation-${CI_RUNNER_TAGS}"
    paths:
      - out/html
      - out/latex
      - out/man
    expire_in: 1h
#  cache: *cache_def

doc:debian:build:
  tags:
    - debian
  <<: *doc_build

doc:freebsd:build:
  tags:
    - freebsd
  <<: *doc_build

doc:opensuse:build:
  tags:
    - opensuse
  <<: *doc_build

.daemon-help:test: &daemon-help_test
  stage: test
  script:
    - out/usbwalld -h || true

daemon-help:debian:test:
  tags:
    - debian
  <<: *daemon-help_test
  dependencies:
    - daemon:debian:build

daemon-help:freebsd:test:
  tags:
    - freebsd
  <<: *daemon-help_test
  dependencies:
    - daemon:freebsd:build

daemon-help:opensuse:test:
  tags:
    - opensuse
  <<: *daemon-help_test
  dependencies:
    - daemon:opensuse:build

.testsuite:test: &testsuite_test
  stage: test
  script:
    - out/usbwall_test

testsuite:debian:test:
  tags:
    - debian
  <<: *testsuite_test
  dependencies:
    - testsuite:debian:build

testsuite:freebsd:test:
  tags:
    - freebsd
  <<: *testsuite_test
  dependencies:
    - testsuite:freebsd:build

testsuite:opensuse:test:
  tags:
    - opensuse
  <<: *testsuite_test
  dependencies:
    - testsuite:opensuse:build
