stages:
  - install
  - build
  - test

debian:
  stage: install
  tags:
    - debian
  script:
    - sudo apt install -y cmake libusb-1.0-0-dev libldap2-dev libpam0g-dev doxygen graphviz

freebsd:
  stage: install
  script:
    - sudo pkg install -y cmake openldap-client
  tags:
    - freebsd

opensuse:
  stage: install
  script:
    - sudo zypper install -y cmake libusb-1_0-devel openldap2-devel pam-devel doxygen graphviz
  tags:
    - opensuse

.build default: &build_default
  allow_failure: true
  stage: build
  before_script:
    - test -d _build && test -d out || ./bootstrap
  script:
    - make
  artifacts:
    name: "default-binaries-${CI_RUNNER_TAGS}"
    paths:
      - out/deviddctl
      - out/libpam_usbwall.so
      - out/usbwalld
    expire_in: 1h
  cache: &cache_def
    paths:
      - _build/
      - out/
    key: ${CI_COMMIT_REF_SLUG}-${CI_RUNNER_TAGS}

default:debian:
  tags:
    - debian
  <<: *build_default

default:freebsd:
  tags:
    - freebsd
  <<: *build_default

default:opensuse:
  tags:
    - opensuse
  <<: *build_default

.build test: &build_test
  allow_failure: true
  stage: build
  before_script:
    - test -d _build && test -d out || ./bootstrap
  script:
    - make test
  artifacts:
    name: "test-binary-${CI_RUNNER_TAGS}"
    paths:
      - out/usbwall_test
    expire_in: 1h
  cache: *cache_def

test:debian:
  tags:
    - debian
  <<: *build_test

test:freebsd:
  tags:
    - freebsd
  <<: *build_test

test:opensuse:
  tags:
    - opensuse
  <<: *build_test

.build doc:debian: &build_doc
  allow_failure: true
  stage: build
  before_script:
    - test -d _build && test -d out || ./bootstrap
  script:
    - make doc
  artifacts:
    name: "documentation-${CI_RUNNER_TAGS}"
    paths:
      - out/html
      - out/latex
      - out/man
    expire_in: 1h
  cache: *cache_def

doc:debian:
  tags:
    - debian
  <<: *build_doc

doc:freebsd:
  tags:
    - freebsd
  <<: *build_doc

doc:opensuse:
  tags:
    - opensuse
  <<: *build_doc

.test daemon help: &test_daemon
  stage: test
  script:
    - out/usbwalld -h || true

daemon_help:debian:
  tags:
    - debian
  <<: *test_daemon
  dependencies:
    - build default:debian

daemon_help:freebsd:
  tags:
    - freebsd
  <<: *test_daemon
  dependencies:
    - build default:freebsd

daemon_help:opensuse:
  tags:
    - opensuse
  <<: *test_daemon
  dependencies:
    - build default:opensuse

.test test: &test_test
  stage: test
  script:
    - out/usbwall_test

test:debian:
  tags:
    - debian
  <<: *test_test
  dependencies:
    - build test:debian

test:freebsd:
  tags:
    - freebsd
  <<: *test_test
  dependencies:
    - build test:freebsd

test:opensuse:
  tags:
    - opensuse
  <<: *test_test
  dependencies:
    - build test:opensuse
