stages:
  - install
  - build
  - test

install environment:debian:
  stage: install
  tags:
    - debian
  script:
    - sudo apt install -y cmake libusb-1.0-0-dev libldap2-dev libpam0g-dev doxygen graphviz

build default:debian:
  allow_failure: true
  stage: build
  tags:
    - debian
  before_script:
    - test -d _build && test -d out || ./bootstrap
  script:
    - make
  artifacts:
    name: "default-binaries"
    paths:
      - out/deviddctl
      - out/libpam_usbwall.so
      - out/usbwalld
    expire_in: 1h
  cache:
    paths:
      - _build/
      - out/
    key: ${CI_COMMIT_REF_SLUG}

build test:debian:
  allow_failure: true
  stage: build
  tags:
    - debian
  before_script:
    - test -d _build && test -d out || ./bootstrap
  script:
    - make test
  artifacts:
    name: "test-binary"
    paths:
      - out/usbwall_test
    expire_in: 1h
  cache:
    paths:
      - _build/
      - out/
    key: ${CI_COMMIT_REF_SLUG}

build doc:debian:
  allow_failure: true
  stage: build
  tags:
    - debian
  before_script:
    - test -d _build && test -d out || ./bootstrap
  script:
    - make doc
  artifacts:
    name: "documentation"
    paths:
      - out/html
      - out/latex
      - out/man
    expire_in: 1h
  cache:
    paths:
      - _build/
      - out/
    key: ${CI_COMMIT_REF_SLUG}
      
test daemon help:debian:
  stage: test
  tags:
    - debian
  script:
    - out/usbwalld -h || true
  dependencies:
    - build default

test test:debian:
  stage: test
  tags:
    - debian
  script:
    - out/usbwall_test
  dependencies:
    - build test
