stages:
  - install
  - prebuild
  - build
  - test
  - deploy

job install:
  stage: install
  script:
    - sudo apt install -y cmake libusb-1.0-0-dev libldap2-dev libpam0g-dev

job prebuild:
  stage: prebuild
  script:
    - ./bootstrap

job build:
  stage: build
  script:
    - make

job test:
  stage: test
  script: make test

job deploy:
  stage: deploy
  script: make install
