stages:
  - install
  - prebuild
  - build
  - test

install environment:
  stage: install
  script:
    - sudo apt install -y cmake libusb-1.0-0-dev libldap2-dev libpam0g-dev doxygen graphviz

staging:
  variables:
    ENVIRONMENT: staging
  stage: install
  trigger: usbwall

prebuild:
  stage: prebuild
  script:
    - test -d _build && test -d out || ./bootstrap
  cache:
    paths:
      - _build/
      - out/
    key: ${CI_COMMIT_REF_SLUG}

build default:
  stage: build
  script:
    - test -d _build && test -d out || ./bootstrap
    - make
  artifacts:
    name: "default-binaries"
    paths:
      - out/deviddctl
      - out/libpam_usbwall.so
      - out/usbwalld
    expire_in: 1h
  cache:
    paths:
      - _build/
      - out/
    key: ${CI_COMMIT_REF_SLUG}

build test:
  stage: build
  script:
    - test -d _build && test -d out || ./bootstrap
    - make test
  artifacts:
    name: "test-binary"
    paths:
      - out/usbwall_test
    expire_in: 1h
  cache:
    paths:
      - _build/
      - out/
    key: ${CI_COMMIT_REF_SLUG}

build doc:
  stage: build
  script:
    - test -d _build && test -d out || ./bootstrap
    - make doc
  artifacts:
    name: "documentation"
    paths:
      - out/html
      - out/latex
      - out/man
    expire_in: 1h
  cache:
    paths:
      - _build/
      - out/
    key: ${CI_COMMIT_REF_SLUG}
      
test daemon help:
  stage: test
  script:
    - out/usbwalld -h || true
  dependencies:
    - build default

test test:
  stage: test
  script:
    - out/usbwall_test
  dependencies:
    - build test
