env:
  global:
    - MAKEFLAGS="-j 4"
language: c
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
dist:
  - trusty
sudo: required
script:
  - ./bootstrap && make
addons:
  apt:
    packages:
      - libpam0g
      - libpam0g-dev
      - libusb-1.0.0
      - libusb-1.0.0-dev
      - libldap-2.4-2
matrix:
  allow_failures:
    - os: osx
