language: c
compiler:
  - clang
  - gcc
os: linux
dist: trusty
sudo: required
script:
  - ./bootstrap DEBUG && make -j
addons:
  apt:
    packages:
      - libpam0g
      - libpam0g-dev
      - libusb-1.0.0
      - libusb-1.0.0-dev
      - libldap-2.4-2
